In [2]:
!python -m pip install numpy

In [4]:
import numpy

In [6]:
import my_file

In [9]:
import keyword

In [11]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [13]:
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [16]:
from keyword import kwlist,iskeyword
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [18]:
iskeyword('if')

True

In [19]:
import numpy as np

In [20]:
a = np.array([])
a

array([], dtype=float64)

In [21]:
b = np.array([3,4,45,4])
b

array([ 3,  4, 45,  4])

In [22]:
len(a)

0

In [23]:
len(b)

4

In [24]:
a.dtype

dtype('float64')

In [25]:
b.dtype

dtype('int32')

In [26]:
b.shape

(4,)

In [27]:
b.shape

(4,)

In [28]:
b.size

4

In [29]:
a.ndim

1

In [30]:
b.ndim

1

In [32]:
type(a)

numpy.ndarray

In [33]:
c = np.array([[2,3,4],[4,5,6],[5,4,6]])
c

array([[2, 3, 4],
       [4, 5, 6],
       [5, 4, 6]])

In [34]:
c.shape

(3, 3)

In [38]:
d = np.array([[[2,5],[3,6],[4,6]],[[4,4],[5,3],[6,5]],[[5,6],[4,3],[6,2]]])
d


array([[[2, 5],
        [3, 6],
        [4, 6]],

       [[4, 4],
        [5, 3],
        [6, 5]],

       [[5, 6],
        [4, 3],
        [6, 2]]])

In [39]:
d.shape

(3, 3, 2)