In [1]:
import numpy as np

In [2]:
np.array([4,3,6,4])

array([4, 3, 6, 4])

In [7]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
# range can generate a simple range,if floating is used in it then it would generate error
#arange is making array,here we can use float numbers(upgraded version of range)

In [9]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.eye(4,2,dtype=int)

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0]])

In [19]:
p = np.eye(4,2)

In [20]:
p.dtype

dtype('float64')

In [21]:
p.astype(int)

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0]])

In [22]:
p.dtype

dtype('float64')

In [25]:
p8 = p.astype('uint8')
p8

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0]], dtype=uint8)

In [26]:
np.random.randint(1,100,5)

array([30, 59, 70, 91, 25])

In [27]:
np.random.randint(1,100,[3,5])

array([[46, 60, 90, 39, 41],
       [78, 84, 49, 42, 22],
       [39, 48, 98, 87, 85]])

In [28]:
np.random.seed(30)
np.random.randint(1,100,[3,5])

array([[38, 38, 46, 46, 13],
       [24,  3, 54, 18, 47],
       [ 4, 42,  8, 66, 50]])

In [30]:
np.random.seed(30) # seed is a function which is generally used to present the same random pattern
np.random.randint(1,100,[3,6])

array([[38, 38, 46, 46, 13, 24],
       [ 3, 54, 18, 47,  4, 42],
       [ 8, 66, 50, 46, 62, 36]])

In [32]:
r = np.random.rand(3,4)
r  

array([[0.17684177, 0.32355352, 0.52936652, 0.93133118],
       [0.96231107, 0.99395971, 0.74929066, 0.38726167],
       [0.37599371, 0.63876234, 0.15681569, 0.9692081 ]])

In [34]:
np.random.randn(3,4)

array([[-0.82521099, -0.66705279, -0.85397035, -0.71430795],
       [-0.16417987, -0.70851243,  1.19756876, -0.72161332],
       [-0.77369404,  1.13031191,  0.03816471, -0.87744236]])

In [38]:
np.loadtxt('data9.txt',dtype='str')

array([['Hey', 'whatsapp', 'guys'],
       ['hpw', 'are', 'you']], dtype='<U8')

In [41]:
np.loadtxt('data9.txt',delimiter=',')

array([[45., 44., 66., 75.],
       [45., 66., 56., 44.],
       [ 1.,  4.,  5.,  6.]])

In [59]:
a = np.random.randint(10,100,[3,5])
a

array([[90, 29, 55, 41, 33],
       [21, 39, 54, 39, 29],
       [86, 61, 95, 65, 62]])

In [60]:
np.savetxt('data3-9.txt',a,delimiter='#',fmt='%d')

In [61]:
sum(a)

array([197, 129, 204, 145, 124])

In [62]:
a.sum()

799

In [49]:
a.sum(axis=1)

array([142, 204])

In [50]:
a.sum(axis=0)

array([149,  77, 120])

In [63]:
a.mean(axis = 1)

array([49.6, 36.4, 73.8])

In [64]:
a.max(axis=1)

array([90, 54, 95])

In [65]:
a.argmax(axis=1)

array([0, 2, 2], dtype=int64)

In [66]:
a.min(axis=0)

array([21, 29, 54, 39, 29])

In [67]:
a.argmin(axis=0)

array([1, 0, 1, 1, 1], dtype=int64)

In [68]:
a.flatten()

array([90, 29, 55, 41, 33, 21, 39, 54, 39, 29, 86, 61, 95, 65, 62])