In [3]:
import numpy as np

In [5]:
a = np.array([5,4,3])
print(a)

[5 4 3]


In [6]:
np.shape(a)

(3,)

In [7]:
a.shape

(3,)

In [34]:
s = np.array([[2,4,6],[5,4,2],[6,8,6]])
s

array([[2, 4, 6],
       [5, 4, 2],
       [6, 8, 6]])

In [15]:
s.shape

(3, 3)

In [28]:
q = np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
q

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [29]:
q.shape

(3, 3, 2)

In [30]:
s[1][0]
s

array([[2, 4, 6],
       [5, 4, 2],
       [6, 8, 6]])

In [35]:
s[1,0]

5

In [36]:
s[2,:]    ## else s[2,0:2:1],s[2,:2],s[2,0:3]

array([6, 8, 6])

In [37]:
s[:,1]

array([4, 4, 8])

In [38]:
s[2]

array([6, 8, 6])

In [39]:
s[:,1:2]

array([[4],
       [4],
       [8]])

In [42]:
s[0:2,1:3]

array([[4, 6],
       [4, 2]])

In [43]:
q[:2,-2:,:1]

array([[[8],
        [7]],

       [[1],
        [5]]])

In [50]:
q

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [56]:
q[2:,1:,:]

array([[[  9,  91],
        [ 13, 131]]])

In [57]:
s

array([[2, 4, 6],
       [5, 4, 2],
       [6, 8, 6]])

In [59]:
s[1] = [44,33,22]
s

array([[ 2,  4,  6],
       [44, 33, 22],
       [ 6,  8,  6]])

In [64]:
s[:,1] = [44,88,69]
s

array([[ 2, 44,  6],
       [44, 88, 22],
       [ 6, 69,  6]])

In [67]:
s + 3
s

array([[ 2, 44,  6],
       [44, 88, 22],
       [ 6, 69,  6]])

In [73]:
np.append(s,[[21,34,23]],axis = 0)

array([[ 2, 44,  6],
       [44, 88, 22],
       [ 6, 69,  6],
       [21, 34, 23]])

In [74]:
np.append(s,[[23],[33],[43]],axis = 1)

array([[ 2, 44,  6, 23],
       [44, 88, 22, 33],
       [ 6, 69,  6, 43]])

In [77]:
np.delete(s,1,axis=1)

array([[ 2,  6],
       [44, 22],
       [ 6,  6]])

In [1]:
#Array creations functions
np.array()
np.arange()
np.linespace()
np.ones()
np.zeros()
np.eye()
np.random.randint()

NameError: name 'np' is not defined

In [ ]:
# pip install opencv-python
# pip install scikit-image
# pip intall matplotlib